### ISSUE TITLE
MakeWaterAcidic ?

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#12]
Spigot 1.13.1 latest
PWP 1.1.3

I have configured
> MakeWaterAcidic: true

but water does not seem to change. I can grab from any water source during a storm, and the water is normal. I can drink it without effect.

**Comment by MostWantedMinx** [comment]
MakeWaterAcidic makes water blocks deal damage ^^

**Comment by SlimeDog** [comment]
Oh, so if I go into the water?

**Comment by SlimeDog** [comment]
Got it!
