### ISSUE TITLE
WORLD placeholder config.yml

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#2]
Spigot 1.13.1 latest
PW 1.1.0 (pre-release)

In config.yml, the placeholder WORLD should use standard placeholder syntax. One of:

- [world]
- {world}
- %world%
- something similar

**Comment by MostWantedMinx** [comment]
Will look into fixing this in the next release of the plugin.

**Comment by MostWantedMinx** [comment]
Added to the new release of the plugin. Will be coming in the next few hours.
