### ISSUE TITLE
Acidic water

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#20]
Spigot 1.13.1 latest
PWP 2.0.2

Acidic water causes damage when player is in creative mode. Damage should occur only in survival (or adventure) mode.

**Comment by MostWantedMinx** [comment]
Will post a bug fix now. for v2.0.3

**Comment by SlimeDog** [comment]
Confirmed fixed in PWP 2.0.3:
- adventure: damage enabled
- creative: damage disabled
- spectator: damage disabled
- survival: damage enabled

Thanks.
