### ISSUE TITLE
Acid water damage when boat cruising

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#22]
Spigot 1.13.1 latest
PWP 2.0.3

Player takes damage while riding in boat across acid water. This should not occur.

**Comment by MostWantedMinx** [comment]
Will fix this in the next few days. Currently very busy. ^^

**Comment by SlimeDog** [comment]
No worries. I am happy to test.

**Comment by MostWantedMinx** [comment]
Will release a build to fix this later today.

**Comment by MostWantedMinx** [comment]
Fixed in 2.0.4
