### ISSUE TITLE
Bad command unknown

### ISSUE THREAD

**Issue by SlimeDog** [MostWantedMinx/My-Plugins#8]
Spigot 1.13.1 latest
PWP 1.1.0

> [21:37:49 INFO]: PyroWeather Unknown command, use /pw for a command list!

The only connected player was AFK, so did not execute a command (player is me).
PWP is used only in a Skript to control weather in the target world. PWP is not called directly. The Skript method is
> execute console command "weather %{_TARGET_WORLD}% storm %{_rand}%"

Configuration includes
> Acidrain.Other.AllStormsAcid: true

which causes acid rain in the target world.

Is there a way to determine the unknown command?

**Comment by SlimeDog** [comment]
Got it.
> essentials:weather does not accept a world argument. Looking for a replacement command, as I need to start rain only in the target world.

**Comment by MostWantedMinx** [comment]
Yeah I'll look into adding per-world storms and such for commands. It's something on that's already on my to-do list but I'll push it up the list some more.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by MostWantedMinx** [comment]
Just read over this again and I totally missed the point some-what. PyroWeather uses the /weather allias. Therefore it will override essentials. For essentials you could also use /rain, /erain and or /eweather. I believe these are all commands that should work and produce the same effect. However, I will add a command to rain in specific worlds in an upcoming update.

**Comment by SlimeDog** [comment]
Oh. Easy to work around, then.
> essentials:weather
